# Generated by Django 5.1 on 2024-09-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('RegisterationNO', models.IntegerField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Course', models.CharField(max_length=100)),
            ],
        ),
    ]
