# Generated by Django 5.1 on 2024-09-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='RegisterationNO',
            field=models.CharField(max_length=100),
        ),
    ]
